#!/usr/bin/env python3
"""Emit ``ops/graph-library-lock.json`` from the Core's own graph library.

The lock is not hand-maintained. A checked-in JSON copy of a table the Python already owns is a
table that will drift, and a drifted dependency lock is worse than none: the compiler refuses an
unpinned child rather than guessing, so a stale lock fails at admission with an error that points at
the graph instead of at the lock. Generating it means the lock and the library cannot disagree.

Run from the repository root:

    PYTHONPATH=services/polyforge/src python3 ops/build-graph-library-lock.py --write

``--check`` is the CI form: it exits non-zero when the committed file differs from what the library
would produce, so a change to a capability, evaluator or policy version cannot land without the lock
being regenerated.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "services" / "polyforge" / "src"))

from polyforge import COMPILER_VERSION, SCHEMA_VERSION
from polyforge.core.compiler.policy_catalog import catalog_versions
from polyforge.graph_library import (
    CAPABILITY_VERSIONS,
    EVALUATOR_VERSIONS,
    dependency_lock_for,
    library_graph_ids,
)

OUTPUT = Path(__file__).resolve().parent / "graph-library-lock.json"


def build() -> dict[str, Any]:
    """The lock document: one entry per library graph, plus the versions it was built against."""
    from polyforge.graph_library import load_graph

    return {
        "$comment": (
            "Generated by ops/build-graph-library-lock.py from services/polyforge/src/polyforge/"
            "graph_library. Do not edit by hand: run the generator and commit the result, or the "
            "compiler will refuse an admission whose pins no longer match the library."
        ),
        "schemaVersion": SCHEMA_VERSION,
        "compilerVersion": COMPILER_VERSION,
        "capabilityVersions": dict(sorted(CAPABILITY_VERSIONS.items())),
        "evaluatorVersions": dict(sorted(EVALUATOR_VERSIONS.items())),
        "policyVersions": dict(sorted(catalog_versions().items())),
        "graphs": {graph_id: dependency_lock_for(graph_id) for graph_id in sorted(library_graph_ids())},
        # The definitions themselves, so an operator tool can publish the real graph.
        #
        # `create_draft` takes the definition from the caller and never guesses one: an empty draft
        # compiles cleanly, so a bootstrap that omitted this published a valid, empty version and
        # reported success. Carrying the definitions here keeps the published graph identical to the
        # library rather than to whatever the client felt like sending.
        "definitions": {
            graph_id: load_graph(graph_id) for graph_id in sorted(library_graph_ids())
        },
    }


def render(document: dict[str, Any]) -> str:
    # Sorted keys and a trailing newline so the file is stable under diff and does not trip the
    # usual "file does not end in newline" noise in review.
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="write the lock file")
    group.add_argument("--check", action="store_true", help="fail if the committed lock is stale")
    args = parser.parse_args(argv)

    expected = render(build())
    if args.write:
        OUTPUT.write_text(expected, encoding="utf-8")
        document = json.loads(expected)
        print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} for {len(document['graphs'])} library graph(s)")
        return 0

    if not OUTPUT.exists():
        print(f"{OUTPUT} does not exist; run this script with --write", file=sys.stderr)
        return 1
    actual = OUTPUT.read_text(encoding="utf-8")
    if actual != expected:
        print(
            f"{OUTPUT.relative_to(REPO_ROOT)} is stale: the graph library, a capability version, an "
            "evaluator version or a policy version has changed since it was generated. "
            "Run: PYTHONPATH=services/polyforge/src python3 ops/build-graph-library-lock.py --write",
            file=sys.stderr,
        )
        return 1
    print(f"{OUTPUT.relative_to(REPO_ROOT)} is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
